cd FedeteriAPI
del trueques.json
del usuarios.json
del articulos.json
del articulos_fedeteria.json
del calificaciones_sucursales.json
del calificaciones_usuarios.json
del codigos.json
del cupones.json

cd bin/Debug/net8.0/
del trueques.json
del usuarios.json
del articulos.json
del articulos_fedeteria.json
del calificaciones_sucursales.json
del calificaciones_usuarios.json
del codigos.json
del cupones.json

cd ../../Release/net8.0/
del trueques.json
del usuarios.json
del articulos.json
del articulos_fedeteria.json
del calificaciones_sucursales.json
del calificaciones_usuarios.json
del codigos.json
del cupones.json
